/* =====================================================================
   QASSIM 40 km — every employer inside a 40 km straight-line radius of
   the pin at 26°07'55.6"N 43°38'37.7"E (Al-Bukayriyah, البكيرية).

   Distances: entries marked `osm: true` are computed from real
   OpenStreetMap coordinates for that exact building. The rest are
   town-centre estimates — treat them as ±3 km, and check the map link
   before you drive anywhere.

   Verified July 2026 from OpenStreetMap, Google Maps, dlilsa.com and each
   employer's own site. Company details change — re-check before applying.
   ===================================================================== */

export const HOME = {
  lat: 26.132111,
  lon: 43.643809,
  label: "Al-Bukayriyah · البكيرية",
  note: "26°07'55.6\"N 43°38'37.7\"E",
};

/* ---------- the eight CV variants, and when each one goes out ---------- */

export const CV_PROFILES = {
  enterprise: {
    icon: "🏭",
    name: "Enterprise / ERP",
    file: "Mahmoud_Alshraky_Resume_Enterprise.pdf",
    headline: "Software Engineer | Enterprise Systems (ERP · HR · Reporting)",
    leads: "HR platform first, then Erth's workflow automation.",
    why: "Factories, cement, poultry and retail groups don't buy 'websites' — they buy internal systems. This version speaks their language: multi-branch data models, payroll and attendance rules, permissions, and management reporting.",
  },
  agency: {
    icon: "🧑‍💻",
    name: "Software house / agency",
    file: "Mahmoud_Alshraky_Resume_Agency.pdf",
    headline: "Full-Stack Web Developer | React · Node.js · PostgreSQL",
    leads: "HR platform, then the two live client sites (law firm, Erth).",
    why: "An agency owner scans for one thing: can this person take a client brief and ship it alone? This version puts four live domains up front.",
  },
  health: {
    icon: "🏥",
    name: "Healthcare",
    file: "Mahmoud_Alshraky_Resume_Health.pdf",
    headline: "Software Engineer | Healthcare & Health-Information Systems",
    leads: "Healthcare HR platform, then the SMLE/SCFHS exam platform.",
    why: "You have the rarest thing a hospital IT manager sees on a junior CV: you already built for a healthcare provider AND for the Saudi medical licensing exam. Lead with that, always.",
  },
  edu: {
    icon: "🎓",
    name: "University / EdTech",
    file: "Mahmoud_Alshraky_Resume_Education.pdf",
    headline: "Software Engineer | EdTech & Learning Platforms",
    leads: "SMLE question bank first — 8,000+ questions, adaptive testing, analytics.",
    why: "A university IT deanship cares about student systems, assessment and dashboards. SMLE is a full assessment platform you built and operate — that's the strongest card in the deck here.",
  },
  gov: {
    icon: "🏛️",
    name: "Government / semi-gov",
    file: "Mahmoud_Alshraky_Resume_Government.pdf",
    headline: "Software Engineer | Digital Services & Arabic-First Systems",
    leads: "HR platform, then the bilingual Erth service portal.",
    why: "Arabic RTL, Hijri dates, RBAC, bilingual portals, automated compliance deadlines — the exact vocabulary of Vision 2030 digital-transformation tenders.",
  },
  ksa: {
    icon: "🇸🇦",
    name: "KSA general",
    file: "Mahmoud_Alshraky_Resume_KSA.pdf",
    headline: "Software Engineer | Computer Science Student",
    leads: "Standard order.",
    why: "Fallback when you can't tell what sector the reader sits in — recruiters, Bayt, LinkedIn Easy Apply.",
  },
  remote: {
    icon: "🌍",
    name: "Remote worldwide",
    file: "Mahmoud_Alshraky_Resume_Remote.pdf",
    headline: "Remote Full-Stack Software Engineer",
    leads: "Standard order.",
    why: "Every job in the Live Jobs feed.",
  },
  ireland: {
    icon: "🇮🇪",
    name: "Ireland / EU",
    file: "Mahmoud_Alshraky_Resume_Ireland.pdf",
    headline: "Software Engineer | Full-Stack",
    leads: "Standard order.",
    why: "Anything where sponsorship comes up.",
  },
  frontend: {
    icon: "⚛️",
    name: "Junior React / Frontend",
    file: "Mahmoud_Alshraky_Resume_Frontend.pdf",
    headline: "Junior React Developer | Frontend Engineer",
    leads: "HR platform (reusable components, dashboards), then SMLE (real-time analytics UI).",
    why: "Junior React/frontend postings that want dashboards, API-wired views, and documentation — not a full-stack generalist pitch.",
  },
};

export const SECTORS = {
  software: { label: "💻 Software houses", color: "#C147E9" },
  edu: { label: "🎓 Universities & colleges", color: "#7fb8ff" },
  health: { label: "🏥 Hospitals & health", color: "#3ecf8e" },
  industry: { label: "🏭 Industry & large groups", color: "#f5a623" },
  gov: { label: "🏛️ Government & semi-gov", color: "#8a8a99" },
};

export const FIT = {
  strong: { label: "🔥 Realistic — apply", color: "#3ecf8e" },
  good: { label: "Worth a shot", color: "#C147E9" },
  stretch: { label: "Indirect route only", color: "#b08c3a" },
};

/* ---------------------------- the employers ---------------------------- */

export const EMPLOYERS = [
  /* ============ RING 1 — 0–15 km · Al-Bukayriyah & Riyadh Al-Khabra ============ */
  {
    id: "sru",
    name: "Sulaiman Al Rajhi University",
    ar: "جامعة سليمان الراجحي",
    city: "Al-Bukayriyah",
    km: 8.7,
    osm: true,
    sector: "edu",
    fit: "strong",
    cv: "edu",
    letter: "ksa_en",
    what: "Non-profit private university (medicine, applied sciences, nursing, business) on the Riyadh–Madinah highway. IT department of roughly 20 people.",
    role: "Software Developer / Web Developer, Deanship of IT — or systems support with a development brief",
    apply: "Careers page + a direct email to recruitment@sr.edu.sa. Private universities hire non-Saudis for IT far more freely than government ones.",
    links: [
      ["Careers", "https://sr.edu.sa/site/careers/"],
      ["Site", "https://sr.edu.sa/"],
      ["Email HR", "mailto:recruitment@sr.edu.sa"],
    ],
    prep: [
      "This is the single closest serious employer to your door — under 10 km. Lead with that: no relocation, no commute risk, available every afternoon.",
      "Founded by the Sulaiman Al Rajhi endowment (waqf), which also runs Al-Watania Poultry and a charitable hospital network. Non-profit — don't open with salary.",
      "Their IT team is small (~20) and skews infrastructure/network. That is exactly where a person who can actually build an internal web app stands out — say 'I build the tools your team doesn't have time to build'.",
      "Concrete pitch: student/staff internal portals, exam and assessment tooling, dashboards. Show SMLE — an 8,000-question adaptive assessment platform is an unusually direct match for a medical university.",
      "Ask about their student information system (likely a commercial SIS). Offer to build the small internal tools around it that vendors charge a fortune for.",
    ],
  },
  {
    id: "sr-hospital",
    name: "Sulaiman Al Rajhi Charitable Hospital & Foundation",
    ar: "مستشفى ومؤسسة سليمان الراجحي الخيرية",
    city: "Al-Bukayriyah",
    km: 9,
    osm: false,
    sector: "health",
    fit: "good",
    cv: "health",
    letter: "ksa_ar",
    what: "The endowment's charitable hospital and foundation operations, on the same campus complex as the university.",
    role: "IT / health-information systems developer",
    apply: "Same HR channel as the university, or walk in with a printed CV — a foundation this close to home is worth one in-person visit.",
    links: [["University careers", "https://sr.edu.sa/site/careers/"]],
    prep: [
      "Same group as the university — one visit can cover both. Ask reception for the IT department directly.",
      "Your Ultimate Care HR platform is a healthcare workforce system. That is the demo to open with: 600+ staff, 25 branches, licence/document expiry alerts.",
      "Charitable/waqf entities run lean and value someone who reduces vendor spend. Frame yourself as internal capability, not as an outside contractor.",
    ],
  },
  {
    id: "jav",
    name: "Jav Advertising (جاف)",
    ar: "جاف للدعاية والإعلان",
    city: "Al-Bukayriyah",
    km: 3.6,
    osm: true,
    sector: "software",
    fit: "strong",
    cv: "agency",
    letter: "ksa_ar",
    what: "Design and advertising agency, essentially on your doorstep.",
    role: "Web developer / technical partner for client projects",
    apply: "Walk in. At 3.6 km there is no excuse not to. Bring a laptop and open alhisony.com and erthfc.com.",
    links: [["Site", "https://www.jav.sa/"]],
    prep: [
      "Design agencies constantly sell websites they then have to outsource. You are the developer they're currently paying someone in another city for.",
      "Don't ask for a job title — ask 'who builds the sites you design?'. If the answer is a freelancer or a template, you have an opening.",
      "Offer per-project pricing first. That sidesteps the whole work-permit conversation and gets you paid work fastest.",
      "Show the law-firm site: Three.js, SEO, Schema.org, custom-domain email. That is agency-grade client work.",
    ],
  },
  {
    id: "bukayriyah-hospital",
    name: "Al-Bukayriyah General Hospital",
    ar: "مستشفى البكيرية العام",
    city: "Al-Bukayriyah",
    km: 2,
    osm: true,
    sector: "health",
    fit: "stretch",
    cv: "health",
    letter: "ksa_ar",
    what: "Ministry of Health general hospital, part of Qassim Health Cluster. Your nearest large workplace of any kind.",
    role: "Health-information / IT support — realistically via a contractor",
    apply: "MoH permanent posts go through the government portal and are effectively Saudi-national only. The real route is the vendor that supplies their systems — ask the IT office who that is.",
    links: [["Qassim Health Cluster", "https://qhc.sa/"]],
    prep: [
      "Be realistic: as a non-Saudi you will not get a direct MoH post. Don't waste weeks on it.",
      "The valuable move is a 10-minute conversation with their IT office asking which company maintains their systems — then apply to THAT company. Health IT vendors hire expats.",
      "It costs one short visit and it's 2 km away.",
    ],
  },
  {
    id: "bukayriyah-municipality",
    name: "Al-Bukayriyah Municipality",
    ar: "بلدية محافظة البكيرية",
    city: "Al-Bukayriyah",
    km: 2,
    osm: false,
    sector: "gov",
    fit: "stretch",
    cv: "gov",
    letter: "ksa_ar",
    what: "Local municipality under Amanat Al-Qassim — permits, services, local e-government.",
    role: "Digital services developer — contractor route only",
    apply: "Government posts are Saudi-national only in practice. What works instead: municipalities tender small digital projects to local firms — find out which firm won theirs.",
    links: [["Amanat Al-Qassim", "https://www.momra.gov.sa/"]],
    prep: [
      "Treat this as market research, not a job application: which local software company holds the municipality contract? That company is your actual target.",
      "Your Erth project (bilingual portal + automated request workflows + Maps integration) is exactly the shape of a municipal service portal — keep it ready as a talking point for whoever holds that contract.",
    ],
  },
  {
    id: "qassim-dates",
    name: "Qassim Dates Factory",
    ar: "مصنع تمور القصيم",
    city: "Between Al-Bukayriyah & Buraydah",
    km: 16.3,
    osm: true,
    sector: "industry",
    fit: "good",
    cv: "enterprise",
    letter: "ksa_ar",
    what: "Date-processing plant — Qassim's signature industry, with real production, inventory and logistics data.",
    role: "Internal systems / ERP developer, or a first project on production reporting",
    apply: "Cold visit or phone. Factories this size rarely post jobs online; they hire whoever shows up with a working solution.",
    links: [],
    prep: [
      "Factories at this scale usually run on Excel plus a basic accounting package. Your opening question: 'how do you track production and stock today?'",
      "Pitch one narrow, obviously valuable thing — a production/inventory dashboard, or barcode-based stock movement — not 'a system'.",
      "Your HR platform proves you can model a messy real operation in 25 tables and make it fast. That is the whole argument.",
      "Qassim exports dates. Anything touching export documentation, batch traceability or expiry has immediate money attached to it.",
    ],
  },
  {
    id: "khabra-hospital",
    name: "Riyadh Al-Khabra General Hospital",
    ar: "مستشفى رياض الخبراء العام",
    city: "Riyadh Al-Khabra",
    km: 12.6,
    osm: true,
    sector: "health",
    fit: "stretch",
    cv: "health",
    letter: "ksa_ar",
    what: "MoH general hospital serving the Riyadh Al-Khabra governorate.",
    role: "Same as Al-Bukayriyah Hospital — vendor route",
    apply: "Same reasoning: MoH direct hiring is closed to you; the systems vendor is the target.",
    links: [["Qassim Health Cluster", "https://qhc.sa/"]],
    prep: ["Only worth a visit if you're already in Riyadh Al-Khabra. Ask the IT office who maintains their systems."],
  },

  /* ============ RING 2 — 15–30 km · the Qassim University corridor ============ */
  {
    id: "qassim-university",
    name: "Qassim University",
    ar: "جامعة القصيم",
    city: "Al-Malida / Buraydah",
    km: 27.3,
    osm: true,
    sector: "edu",
    fit: "strong",
    cv: "edu",
    letter: "ksa_en",
    what: "Your own university. Deanship of Information Technology plus a College of Computer at ~28 km, and dozens of funded research projects that need software built.",
    role: "Student developer / research assistant / part-time developer on a funded project",
    apply: "Not through the jobs portal — through people. Your own professors in the College of Computer are the highest-probability route to paid work you have anywhere in this list.",
    links: [
      ["University", "https://www.qu.edu.sa/"],
      ["College of Computer", "https://cc.qu.edu.sa/"],
    ],
    prep: [
      "This is your single biggest unfair advantage and you're already inside it. A student who has shipped a 25-table production system is rare, and your faculty don't know it yet.",
      "Concrete action: email 3–5 professors in the College of Computer with a two-line pitch and links to SMLE + the HR platform. Ask if any funded project needs a developer. This costs one evening.",
      "Research projects and deanship units pay students for development work through routes that avoid the full employment-permit problem — ask explicitly how student project work is paid.",
      "Also ask about the Deanship of IT's internal tooling. Universities are drowning in small internal systems nobody has time to build.",
      "Referrals from faculty are the most reliable way into every other employer in this list too. Treat professors as your network, not just your teachers.",
    ],
  },
  {
    id: "hayat-hospital",
    name: "Al Hayat National Hospital",
    ar: "مستشفى الحياة الوطني",
    city: "Buraydah area",
    km: 29.9,
    osm: true,
    sector: "health",
    fit: "strong",
    cv: "health",
    letter: "ksa_en",
    what: "Private hospital group (hayathospitals.com) with multiple KSA locations.",
    role: "IT / health-information systems developer",
    apply: "HR email + LinkedIn. Private hospitals hire expat IT staff routinely — this is a genuinely open door, unlike the MoH ones.",
    links: [["Site", "https://hayathospitals.com/"]],
    prep: [
      "Private hospital = private hiring rules. This is the most realistic hospital on the list for you.",
      "Your Ultimate Care HR platform IS a private-healthcare workforce system. Same problem space: staff across branches, licence and document expiry, Arabic reporting. Say so in the first paragraph.",
      "Staff-credential expiry (SCFHS licences, iqamas, contracts) is a genuine compliance pain for every private hospital, and you already built automated 30/60/90-day alerts for it. That's your hook.",
      "Second hook: SMLE. Their physicians sit that exam. You built the platform they study on. It's an instant conversation.",
    ],
  },
  {
    id: "qassim-military-hospital",
    name: "Qassim Military Hospital",
    ar: "المستشفى العسكري بالقصيم",
    city: "North-east of Al-Bukayriyah",
    km: 23.7,
    osm: true,
    sector: "health",
    fit: "stretch",
    cv: "health",
    letter: "ksa_ar",
    what: "Ministry of Defense hospital.",
    role: "IT — restricted",
    apply: "Security clearance and nationality requirements make this closed in practice. Listed for completeness only.",
    links: [],
    prep: ["Don't spend time here. Listed so you know it exists and can rule it out."],
  },

  /* ============ RING 3 — 30–40 km · Ar-Rass, Unaizah, Buraydah ============ */
  {
    id: "codlop",
    name: "Codlop (كود لوب)",
    ar: "كود لوب لتقنية المعلومات",
    city: "Buraydah",
    km: 39,
    osm: false,
    sector: "software",
    fit: "strong",
    cv: "agency",
    letter: "ksa_ar",
    what: "Buraydah software house, 10+ years, registered with Monshaat / Ministry of Commerce / Etimad. Websites, mobile apps, hosting, digital marketing, government-facing work.",
    role: "Full-stack / front-end developer",
    apply: "WhatsApp their published numbers (+966 55 870 6532 · +966 54 454 7990) with a two-line intro and your portfolio link. Arabic message.",
    links: [
      ["Site", "https://codlop.sa/"],
      ["Facebook", "https://www.facebook.com/codlop.sa/"],
    ],
    prep: [
      "Etimad registration means they bid on government contracts — they need people who can deliver Arabic RTL systems on deadline. That's you.",
      "Send in Arabic, keep it under five lines, and put the three live domains in the first message. Agencies decide from links, not CVs.",
      "Ask about project-based work first. Getting one paid project is faster than getting hired, and it converts.",
      "They do IoT content on their blog — if they're moving into IoT dashboards, mention your real-time analytics work on SMLE.",
    ],
  },
  {
    id: "mte",
    name: "MTE Information Technology",
    ar: "ام تي اي لتقنية المعلومات",
    city: "Buraydah",
    km: 39,
    osm: false,
    sector: "software",
    fit: "strong",
    cv: "agency",
    letter: "ksa_ar",
    what: "Saudi IT firm based in Buraydah (Ali bin Abi Talib Road, Al-Amn district) — computer services and web development.",
    role: "Web developer",
    apply: "Contact form on mte.sa, then follow up by phone. Small firms answer phones, not inboxes.",
    links: [["Site", "https://www.mte.sa/"]],
    prep: [
      "Read their portfolio page before contacting and name one specific project you liked. Nobody does this, and it works.",
      "Firms this size need someone who can do front-end AND back-end AND deploy. That's your exact shape — say it in one sentence.",
    ],
  },
  {
    id: "inter",
    name: "Inter Company for Communications & IT",
    ar: "شركة انتر للاتصالات وتقنية المعلومات",
    city: "Buraydah (Al-Sadah, former Al-Rajhi building)",
    km: 39,
    osm: false,
    sector: "software",
    fit: "strong",
    cv: "agency",
    letter: "ksa_ar",
    what: "LLC founded 2009, headquartered in Buraydah. Consulting, computer services, networks, IT.",
    role: "Software developer / IT consultant",
    apply: "Phone or in-person. Established 2009 means real clients and real maintenance contracts.",
    links: [],
    prep: [
      "Their business skews networks and consulting — which usually means their software delivery is outsourced or thin. That's the gap you fill.",
      "Sixteen years of clients means a backlog of small internal systems people have asked for. Ask what they've turned down for lack of a developer.",
    ],
  },
  {
    id: "efhas",
    name: "Check For It / Efhas Technologies",
    ar: "افحص لتقنية المعلومات",
    city: "Buraydah",
    km: 39,
    osm: false,
    sector: "software",
    fit: "strong",
    cv: "enterprise",
    letter: "ksa_ar",
    what: "Buraydah IT firm building business-management and accounting software for Saudi SMEs, positioned around Vision 2030.",
    role: "Full-stack developer on their product",
    apply: "Direct contact. This is a product company, not a project shop — they need long-term developers.",
    links: [["Site", "https://aldqh.com/"]],
    prep: [
      "Business/accounting software in Saudi means ZATCA e-invoicing (Fatoora) integration. Read up on Phase 2 integration requirements before you talk to them — one hour of reading makes you sound like an insider.",
      "Use the Enterprise CV here, not the agency one. Their world is data models and reporting, not landing pages.",
      "Your HR platform's payroll, attendance and Hijri/Gregorian reporting is the closest thing on your CV to what they sell.",
    ],
  },
  {
    id: "ultimate-solutions",
    name: "Ultimate Solutions for Computer Works",
    ar: "الحلول النهائية لأعمال الحاسب الآلي",
    city: "Buraydah — King Abdullah Rd, opposite Al Baik",
    km: 39,
    osm: false,
    sector: "software",
    fit: "strong",
    cv: "agency",
    letter: "ksa_ar",
    what: "Listed on Google Maps as a software company (شركة برمجيات), 4.7★. Buraydah branch on King Abdullah Road.",
    role: "Developer",
    apply: "Phone 058 188 0681, or walk in — they open Sunday 9 AM. Easy to combine with any other Buraydah visit.",
    links: [],
    prep: [
      "A 4.7 rating with real reviews means an active client base. Read the reviews first — they tell you what the company actually sells.",
      "'Branch' in the name implies a head office elsewhere. Ask where, and whether the head office hires developers.",
    ],
  },
  {
    id: "rossum",
    name: "Rossum Programming",
    ar: "مؤسسة روسم للبرمجة",
    city: "Buraydah — Abu Bakr Al-Siddiq Rd, Al-Nahda",
    km: 39,
    osm: false,
    sector: "software",
    fit: "strong",
    cv: "agency",
    letter: "ksa_ar",
    what: "Buraydah software house — website and application development and design.",
    role: "Developer",
    apply: "In person or by phone via the directory listing.",
    links: [],
    prep: [
      "A pure programming shop — the pitch is simply React + Node + PostgreSQL with four live production sites, no explanation needed.",
      "Small shops care most about whether you can be handed a client and left alone. Say the word 'solo' about at least two projects.",
    ],
  },
  {
    id: "digital-creativity",
    name: "Digital Creativity Foundation",
    ar: "مؤسسة الابداع الرقمي لتقنية المعلومات",
    city: "Buraydah — Omar bin Salim St, Al-Bishr",
    km: 39,
    osm: false,
    sector: "software",
    fit: "good",
    cv: "agency",
    letter: "ksa_ar",
    what: "Saudi firm specialising in website design, hosting and programming.",
    role: "Web developer",
    apply: "Direct contact via directory listing.",
    links: [],
    prep: [
      "Hosting-plus-design shops tend to be WordPress-heavy. If you can also handle custom React/Node work, you're an upgrade rather than a duplicate — lead with that.",
    ],
  },
  {
    id: "urghwani",
    name: "Urghwani (أورغواني)",
    ar: "أورغواني",
    city: "Buraydah",
    km: 39,
    osm: false,
    sector: "software",
    fit: "good",
    cv: "agency",
    letter: "ksa_ar",
    what: "Creative digital-marketing agency doing WordPress design and development.",
    role: "Web developer / freelance partner",
    apply: "Direct contact. Best framed as freelance overflow capacity.",
    links: [],
    prep: [
      "Marketing agencies win the client and then need someone to build. Position yourself as the build half, available per project.",
      "Speed and performance are what they can resell. Your Erth result (40% faster response, 1.8× repeat requests) is the kind of number an agency loves to quote.",
    ],
  },
  {
    id: "daw-shamel",
    name: "Light of Comprehensive Computers Co.",
    ar: "شركة ضوء الشامل للحاسبات المحدودة",
    city: "Buraydah — King Abdullah Rd, Al-Safra",
    km: 39,
    osm: false,
    sector: "software",
    fit: "good",
    cv: "agency",
    letter: "ksa_ar",
    what: "Computer company (LLC) doing electronics retail, computer services and website development.",
    role: "Web developer",
    apply: "Walk-in. Retail-facing means someone is always at the counter.",
    links: [],
    prep: ["Retail + services businesses often want their own e-commerce or inventory system. Ask what they use internally — the answer is usually 'nothing good'."],
  },
  {
    id: "tkamel",
    name: "Takamul Technology",
    ar: "شركة تكامل التقنية",
    city: "Buraydah",
    km: 39.6,
    osm: true,
    sector: "software",
    fit: "good",
    cv: "agency",
    letter: "ksa_ar",
    what: "IT company at the far edge of your radius, with its own site.",
    role: "Developer",
    apply: "Site contact form, then phone.",
    links: [["Site", "https://www.tkamel.com/"]],
    prep: ["Check their services page first — 'تكامل' (integration) usually means systems integration work, which is where enterprise experience matters more than front-end polish. If so, send the Enterprise CV instead."],
  },
  {
    id: "pcd",
    name: "PC Doctor (طبيب الكمبيوتر)",
    ar: "طبيب الكمبيوتر",
    city: "Ar-Rass / Buraydah area",
    km: 30.7,
    osm: true,
    sector: "software",
    fit: "good",
    cv: "agency",
    letter: "ksa_ar",
    what: "Computer services company (pcd.com.sa).",
    role: "Developer / technical",
    apply: "Site contact.",
    links: [["Site", "https://pcd.com.sa/"]],
    prep: ["Likely services and repair rather than development — verify before spending effort. If they do any software, they're a small enough shop that one good conversation decides it."],
  },
  {
    id: "awar",
    name: "Awar Marketing Services",
    ar: "أوّار للخدمات التسويقية",
    city: "Unaizah — Omar bin Al-Khattab Rd, Al-Khalidiyah",
    km: 35,
    osm: false,
    sector: "software",
    fit: "good",
    cv: "agency",
    letter: "ksa_ar",
    what: "Digital marketing agency: content, graphics, motion, paid ads, website design.",
    role: "Web developer (freelance / per project)",
    apply: "Instagram or WhatsApp — marketing agencies live on social, not email.",
    links: [],
    prep: [
      "Same play as Urghwani: they sell sites, someone has to build them. Offer per-project pricing.",
      "Unaizah is a separate city from Buraydah with its own client base — worth treating as its own market rather than an afterthought.",
    ],
  },
  {
    id: "qassim-cement",
    name: "Qassim Cement Company",
    ar: "شركة أسمنت القصيم",
    city: "Buraydah",
    km: 38,
    osm: false,
    sector: "industry",
    fit: "strong",
    cv: "enterprise",
    letter: "ksa_en",
    what: "Tadawul-listed cement producer, founded 1976, 500–1,000 employees. Acquired Hail Cement in 2024, so it now runs multi-site operations.",
    role: "IT / applications developer, ERP support, reporting analyst",
    apply: "They have a real careers portal — qcc.com.sa/Careers. Also apply via LinkedIn and Bayt; listed companies actually use them.",
    links: [
      ["Careers", "https://qcc.com.sa/Careers/en/"],
      ["Site", "https://qcc.com.sa/"],
      ["LinkedIn", "https://www.linkedin.com/company/qassim-cement-company"],
    ],
    prep: [
      "The biggest formal employer on this list with a working online application process. Apply properly, in English, with the Enterprise CV.",
      "A listed company files quarterly. Read the last Tadawul announcement before any interview — knowing their production capacity and the Hail acquisition puts you ahead of every other junior applicant.",
      "Industrial IT runs on ERP (likely SAP or Oracle). You won't have that on your CV — don't pretend. Say instead: 'I built a 25-table system from scratch, so I understand the data model underneath an ERP, and I learn fast.'",
      "The multi-site angle after the Hail acquisition is your strongest parallel: your HR platform already handles 25 branches with per-branch permissions.",
      "Realistic entry point is a support/reporting role that grows into development. Take it — a listed company on your CV changes every later application.",
    ],
  },
  {
    id: "alwasail",
    name: "Al Wasail Industrial Company",
    ar: "شركة الوسائل الصناعية",
    city: "Buraydah industrial area",
    km: 38.9,
    osm: true,
    sector: "industry",
    fit: "strong",
    cv: "enterprise",
    letter: "ksa_en",
    what: "Industrial manufacturer with its own web presence (alwasail.com) in the Buraydah industrial zone.",
    role: "IT / internal systems developer",
    apply: "Careers or contact page, plus LinkedIn.",
    links: [["Site", "https://www.alwasail.com/"]],
    prep: [
      "Manufacturers this size usually have one or two IT people covering everything. Your value is being the person who can actually build, not just maintain.",
      "Read their product lines before contacting so you can name what they make. Industrial firms notice when an applicant knows their business.",
      "Production dashboards, maintenance scheduling and inventory are the standard unmet needs. Pick one and pitch it concretely.",
    ],
  },
  {
    id: "daajan",
    name: "Al Daajan Holdings",
    ar: "الدجاجن القابضة",
    city: "Ar-Rass / Buraydah area",
    km: 31.4,
    osm: true,
    sector: "industry",
    fit: "good",
    cv: "enterprise",
    letter: "ksa_ar",
    what: "Holding company inside the radius, listed on the map as a company office.",
    role: "IT / internal systems",
    apply: "Cold approach — research the group's subsidiaries first.",
    links: [],
    prep: [
      "Holding companies are worth a search because one approach can reach several subsidiaries. Find out what they actually own before contacting.",
      "Group-level HR and reporting across subsidiaries is exactly the multi-branch problem you already solved.",
    ],
  },
  {
    id: "mustaqbal",
    name: "Mustaqbal University",
    ar: "جامعة المستقبل",
    city: "Buraydah",
    km: 33.3,
    osm: true,
    sector: "edu",
    fit: "strong",
    cv: "edu",
    letter: "ksa_en",
    what: "The first private university in Qassim, with a College of Engineering & Computer Science (computer science, information systems, computer engineering, IT).",
    role: "Developer in university IT, or teaching/lab assistant with a development component",
    apply: "HR via uom.edu.sa. Private university, so non-Saudi hiring is normal.",
    links: [
      ["Site", "https://uom.edu.sa/"],
      ["Engineering & IT college", "https://engineering.futureuniversity.com/"],
    ],
    prep: [
      "They teach CS but are a young private institution — their internal systems are probably still being built. Good timing.",
      "You are a CS student at the region's flagship public university who has shipped production software. For a private university trying to prove its programme is practical, that story has value beyond just your code.",
      "Ask about lab-assistant and teaching-assistant openings as well as IT. Both are afternoon-compatible with your own schedule.",
    ],
  },
  {
    id: "buraydah-colleges",
    name: "Buraydah Private Colleges",
    ar: "كليات بريدة الأهلية",
    city: "Buraydah",
    km: 31.7,
    osm: true,
    sector: "edu",
    fit: "good",
    cv: "edu",
    letter: "ksa_ar",
    what: "Private colleges complex in Buraydah.",
    role: "IT / systems developer",
    apply: "HR office directly, in person or by phone.",
    links: [],
    prep: [
      "Same logic as Mustaqbal: private education hires expats, and their internal tooling is usually thin.",
      "Student portals, attendance, exam systems — SMLE proves you've built assessment software that real users depend on.",
    ],
  },
  {
    id: "unaizah-tech-college",
    name: "Unaizah Technical College (TVTC)",
    ar: "الكلية التقنية في عنيزة",
    city: "Unaizah",
    km: 33.5,
    osm: true,
    sector: "edu",
    fit: "stretch",
    cv: "edu",
    letter: "ksa_ar",
    what: "Technical and Vocational Training Corporation college.",
    role: "Trainer / lab support — government body",
    apply: "TVTC is a government corporation; direct hiring favours Saudi nationals. Occasionally contracts external trainers.",
    links: [["TVTC", "https://tvtc.gov.sa"]],
    prep: [
      "Long shot for employment, but worth knowing: TVTC runs short professional courses and sometimes contracts outside instructors.",
      "If you ever want teaching income, a web-development short course here is the realistic version of that.",
    ],
  },
  {
    id: "qassim-health-cluster",
    name: "Qassim Health Cluster",
    ar: "تجمع القصيم الصحي",
    city: "Buraydah (HQ)",
    km: 39,
    osm: false,
    sector: "health",
    fit: "stretch",
    cv: "health",
    letter: "ksa_ar",
    what: "The region's health authority: about 20 hospitals and 156 primary-care centres, serving over a million people. Runs a large health-informatics operation.",
    role: "Health-informatics developer — vendor route",
    apply: "Direct posts and the Tamheer programme are for Saudi nationals. The route in is the private companies that build and maintain their systems.",
    links: [
      ["Cluster site", "https://qhc.sa/"],
      ["Health Holding Co.", "https://www.health.sa/ar/clusters/al-qassim_health_cluster"],
    ],
    prep: [
      "Don't apply directly — you'll be filtered on nationality. Use it as a map of demand instead.",
      "Twenty hospitals and 156 centres means a long list of suppliers. Identify two or three of those suppliers and apply to them with the Health CV.",
      "Their published technical vacancies (network and computer support) tell you what skills they buy. Useful intel even if the door is closed.",
    ],
  },
  {
    id: "habib-qassim",
    name: "Dr. Sulaiman Al Habib Hospital — Qassim",
    ar: "مستشفى الدكتور سليمان الحبيب بالقصيم",
    city: "Buraydah",
    km: 39.6,
    osm: true,
    sector: "health",
    fit: "strong",
    cv: "health",
    letter: "ksa_en",
    what: "Branch of Saudi Arabia's largest private healthcare group (HMG), Tadawul-listed with a serious in-house technology division.",
    role: "Software developer / health-IT — group careers portal",
    apply: "Apply to the GROUP, not the branch: hmg.com careers plus LinkedIn. HMG runs real software teams and hires non-Saudis.",
    links: [
      ["HMG careers", "https://hmg.com/en/Pages/careers.aspx"],
      ["LinkedIn", "https://www.linkedin.com/company/dr-sulaiman-al-habib-medical-group"],
    ],
    prep: [
      "The most professional healthcare employer within reach, and the one most likely to have a genuine software engineering track.",
      "HMG built its own hospital information systems and patient apps in-house — that's a real engineering organisation, not just an IT support desk.",
      "Most roles will be in Riyadh. Apply anyway, and say you're open to remote or to the Qassim branch. Your remote CV variant exists for exactly this.",
      "Lead with the healthcare HR platform and SMLE. In a hospital group, both land instantly.",
    ],
  },
  {
    id: "qassim-specialist",
    name: "Qassim Specialist Medical Center",
    ar: "مركز القصيم الطبي التخصصي",
    city: "Unaizah / Buraydah area",
    km: 34.4,
    osm: true,
    sector: "health",
    fit: "good",
    cv: "health",
    letter: "ksa_ar",
    what: "Private specialist medical centre.",
    role: "IT / systems developer",
    apply: "Direct approach to the administration or IT office.",
    links: [],
    prep: [
      "Private medical centres of this size run a commercial HIS and almost nothing else. Everything around it — appointments, staff documents, reporting — is manual.",
      "One concrete offer beats a general CV: an automated staff-credential expiry tracker, which you have already built once.",
    ],
  },
  {
    id: "amanat-qassim",
    name: "Amanat Al-Qassim (Regional Municipality)",
    ar: "أمانة منطقة القصيم",
    city: "Buraydah",
    km: 38.5,
    osm: true,
    sector: "gov",
    fit: "stretch",
    cv: "gov",
    letter: "ksa_ar",
    what: "Regional municipal authority — permits, projects, urban services, and the region's e-services.",
    role: "Digital services developer — contractor route",
    apply: "Government employment is Saudi-national only in practice. Real route: the contractors who deliver their digital projects, found via the Etimad tender platform.",
    links: [
      ["Etimad tenders", "https://tenders.etimad.sa/"],
      ["MOMRA", "https://www.momra.gov.sa/"],
    ],
    prep: [
      "Learn to read Etimad. Public tenders show you exactly which local companies win government software work — that list is a hiring target list you can't get any other way.",
      "This single habit is worth more than a hundred cold applications: find the winners, apply to them with the Government CV.",
    ],
  },
  {
    id: "qassim-chamber",
    name: "Qassim Chamber of Commerce",
    ar: "غرفة القصيم",
    city: "Buraydah",
    km: 39,
    osm: false,
    sector: "gov",
    fit: "good",
    cv: "gov",
    letter: "ksa_ar",
    what: "The regional chamber — the membership directory of essentially every registered business in Qassim, plus events and training.",
    role: "Not primarily an employer — a lead source",
    apply: "Use it as a directory and a networking venue rather than a job application.",
    links: [
      ["Qassim Chamber", "https://qcci.org.sa/"],
      ["Ar-Rass Chamber", "https://alrasscci.org.sa/"],
    ],
    prep: [
      "The chamber's member directory is the most complete list of local companies that exists — far better than any online business directory.",
      "Chambers run business events and training. Attending one puts you in a room with the owners who make hiring decisions, which no online application does.",
      "Ar-Rass Chamber is only ~32 km away and much smaller, meaning it's easier to actually get to know people there.",
    ],
  },
  {
    id: "stc-qassim",
    name: "STC · Mobily · Zain — Qassim offices",
    ar: "الاتصالات السعودية · موبايلي · زين",
    city: "Buraydah / Unaizah",
    km: 32.2,
    osm: true,
    sector: "gov",
    fit: "stretch",
    cv: "ksa",
    letter: "ksa_en",
    what: "Regional offices and stores of the three national telecom operators (STC 32 km, Zain 33 km, Mobily 34 km).",
    role: "Engineering roles exist — but in Riyadh, not here",
    apply: "Apply through the national careers portals, not the local branch. Branch staff cannot route a developer CV anywhere useful.",
    links: [
      ["STC careers", "https://careers.stc.com.sa/"],
      ["Mobily careers", "https://www.mobily.com.sa/en/careers"],
      ["Zain careers", "https://www.sa.zain.com/en/about-zain/careers"],
    ],
    prep: [
      "The local presence is retail. Don't confuse a shop with an employer for your skill set.",
      "Worth an application through the national portal anyway — STC in particular runs large digital units and hires non-Saudis for technical roles. Use the KSA or Remote CV.",
    ],
  },
  {
    id: "sec-qassim",
    name: "Saudi Electricity Co. & National Water Co.",
    ar: "الشركة السعودية للكهرباء · شركة المياه الوطنية",
    city: "Al-Bukayriyah office 2.3 km · Buraydah ~40 km",
    km: 2.3,
    osm: true,
    sector: "gov",
    fit: "stretch",
    cv: "gov",
    letter: "ksa_ar",
    what: "National utilities with service offices inside the radius — including a Saudi Electricity office 2.3 km from you.",
    role: "Corporate IT — centralised, not local",
    apply: "National careers portals only. The nearby offices are customer-service branches.",
    links: [
      ["SEC careers", "https://www.se.com.sa/en-us/Careers"],
      ["NWC careers", "https://www.nwc.com.sa/"],
    ],
    prep: [
      "Listed because they're physically close and people assume proximity means opportunity. It doesn't — technical hiring is centralised in Riyadh.",
      "Utilities do outsource large digital projects. Same Etimad trick applies: find the contractor, apply there.",
    ],
  },
  {
    id: "kacst-qassim",
    name: "KACST — Qassim presence",
    ar: "مدينة الملك عبدالعزيز للعلوم والتقنية",
    city: "Buraydah area",
    km: 32.8,
    osm: true,
    sector: "gov",
    fit: "good",
    cv: "gov",
    letter: "ksa_en",
    what: "King Abdulaziz City for Science and Technology — the national research body, with a mapped presence in the region.",
    role: "Research software developer / research assistant",
    apply: "Through KACST's national portal and through research collaborations — often easier via a Qassim University professor than through HR.",
    links: [["KACST", "https://www.kacst.gov.sa/"]],
    prep: [
      "Research bodies hire on the strength of a project and a supervisor's recommendation, which suits you far better than a nationality-filtered HR portal.",
      "Combine this with the Qassim University action: when you email professors, ask specifically whether any of their funded work runs through KACST.",
    ],
  },
  {
    id: "saudi-post",
    name: "Saudi Post (SPL) — Qassim",
    ar: "البريد السعودي",
    city: "Ar-Rass / Buraydah",
    km: 31.8,
    osm: true,
    sector: "gov",
    fit: "stretch",
    cv: "gov",
    letter: "ksa_ar",
    what: "National postal and logistics operator with a strong digital arm (Wasel, national address system).",
    role: "Developer — Riyadh-centralised",
    apply: "National careers portal.",
    links: [["SPL", "https://splonline.com.sa/"]],
    prep: ["Local branches are counters. Technical roles are in Riyadh — apply nationally or skip."],
  },
  {
    id: "ojeen",
    name: "Ojeen Trading Co.",
    ar: "شركة أوجين للتجارة المحدودة",
    city: "Buraydah area",
    km: 38.9,
    osm: true,
    sector: "industry",
    fit: "good",
    cv: "enterprise",
    letter: "ksa_ar",
    what: "Trading company with its own website inside the radius.",
    role: "Internal systems / e-commerce developer",
    apply: "Site contact form.",
    links: [["Site", "https://www.ojeenltd.com/"]],
    prep: [
      "Trading companies need inventory, orders and supplier data joined up — a normal database problem you can solve.",
      "Check whether their site sells online. If it doesn't, that's your pitch; if it does, ask who maintains it.",
    ],
  },
  {
    id: "shams-altabia",
    name: "Shams Al Tabia (Natural Solar Energy)",
    ar: "شمس الطبيعة للطاقة الشمسية",
    city: "Unaizah area",
    km: 35,
    osm: true,
    sector: "industry",
    fit: "good",
    cv: "enterprise",
    letter: "ksa_ar",
    what: "Solar energy company operating inside the radius.",
    role: "Developer — monitoring dashboards, quoting tools",
    apply: "Site contact.",
    links: [["Site", "https://www.shamsaltabia.com/"]],
    prep: [
      "Solar installers need two things built: a sizing/quoting calculator for sales, and a monitoring dashboard for installed systems. Both are well within what you've already built.",
      "Renewables is a growth sector under Vision 2030 — a good story to have on your CV in two years.",
    ],
  },
];

/* Order the CV variants are shown in: the three market variants, then the five
   sector variants used by the employers above. */
export const CV_ORDER = ["ksa", "remote", "frontend", "ireland", "enterprise", "agency", "health", "edu", "gov"];

/* Distance rings used to group the list. */
export const RINGS = [
  { key: "r1", label: "0–15 km · Al-Bukayriyah & Riyadh Al-Khabra", max: 15, note: "Walking-and-driving distance. Your home turf — visit in person." },
  { key: "r2", label: "15–30 km · Qassim University corridor", max: 30, note: "About 20–25 minutes. Reachable after class." },
  { key: "r3", label: "30–40 km · Ar-Rass · Unaizah · Buraydah", max: 40, note: "30–40 minutes. Where most of the region's employers actually are — batch several visits into one trip." },
];
